-- MySQL Script generated by MySQL Workbench
-- Mon 19 Sep 2016 09:32:30 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wearablelearning
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wearablelearning
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wearablelearning` DEFAULT CHARACTER SET utf8 ;
USE `wearablelearning` ;

-- -----------------------------------------------------
-- Table `wearablelearning`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wearablelearning`.`class` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `teacherId` INT NOT NULL,
  `className` VARCHAR(45) NOT NULL,
  `grade` INT NOT NULL,
  `school` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wearablelearning`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wearablelearning`.`teacher` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `school` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wearablelearning`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wearablelearning`.`student` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NULL,
  `age` INT NULL,
  `classId` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wearablelearning`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wearablelearning`.`games` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `teamCount` INT NOT NULL,
  `playerPerTeam` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
